#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
superdir="$(git rev-parse --show-superproject-working-tree)"
if [ -z "${superdir}" ]
then
  dir="$(git rev-parse --git-dir)"
else
  dir="${superdir}/.git"
fi

trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files --recurse-submodules | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql \
  >/dev/null 2>&1
mv "$dir/$$.tags" "$dir/tags"
