#!/bin/bash

scrot /tmp/screenshot.png
# convert /tmp/screenshot.png -resize 10% -filter point -resize 1000% /tmp/screenshotblur.png
convert /tmp/screenshot.png -spread 10 /tmp/screenshot.png
i3lock -i /tmp/screenshot.png -n
